"""Sanity gate for ``wiki/data/small_l3_thrash.{csv,json,md}``.

The small-L3 thrash report is generated by
``scripts/experiments/ecg/small_l3_thrash_report.py`` from the
standalone ``final_cache_sim`` sweep. This module asserts:

1. All three artifacts exist and are non-empty.
2. CSV and JSON describe the same set of (graph, app, l3_size) cells.
3. Every winner is a known policy label.
4. Every miss-rate is in [0, 1].
5. The headline paper claim holds: in the tiny-L3 regime, **LRU wins
   at least one cell** where GRASP and POPT both regress badly
   (>= 5 pp worse than LRU). This catches accidental file swaps where
   the lit-faith CSV is plotted instead of the thrash CSV.
6. POPT_CHARGED never wins — the charged variant pays an overhead that
   makes it ≥ all uncharged baselines in this regime.
7. ECG variants are present (regression guard against accidental
   policy-dropout in the sweep).
"""

from __future__ import annotations

import csv
import json
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
CSV_PATH = REPO_ROOT / "wiki" / "data" / "small_l3_thrash.csv"
JSON_PATH = REPO_ROOT / "wiki" / "data" / "small_l3_thrash.json"
MD_PATH = REPO_ROOT / "wiki" / "data" / "small_l3_thrash.md"

KNOWN_POLICIES = {
    "LRU", "SRRIP", "GRASP", "POPT", "POPT_CHARGED",
    "ECG_DBG_ONLY", "ECG_DBG_PRIMARY", "ECG_DBG_PRIMARY_CHARGED",
    "ECG_POPT_PRIMARY",
}

REQUIRED_ECG_LABELS = {
    "ECG_DBG_ONLY", "ECG_DBG_PRIMARY",
    "ECG_DBG_PRIMARY_CHARGED", "ECG_POPT_PRIMARY",
}


def _require(path: Path) -> None:
    if not path.exists():
        pytest.skip(
            f"{path.relative_to(REPO_ROOT)} not on disk. "
            f"Run `python3 -m scripts.experiments.ecg.small_l3_thrash_report`."
        )


@pytest.fixture(scope="module")
def csv_rows() -> list[dict]:
    _require(CSV_PATH)
    with CSV_PATH.open(newline="") as fh:
        return list(csv.DictReader(fh))


@pytest.fixture(scope="module")
def payload() -> dict:
    _require(JSON_PATH)
    return json.loads(JSON_PATH.read_text())


def test_artifacts_exist() -> None:
    for p in (CSV_PATH, JSON_PATH, MD_PATH):
        _require(p)
        assert p.stat().st_size > 0, f"{p} is empty"


def test_csv_and_json_have_same_cells(csv_rows: list[dict], payload: dict) -> None:
    csv_cells = {(r["graph"], r["app"], r["l3_size"]) for r in csv_rows}
    json_cells = {(c["graph"], c["app"], c["l3_size"]) for c in payload["cells"]}
    assert csv_cells == json_cells, (
        f"CSV/JSON cell sets disagree. "
        f"only_csv={sorted(csv_cells - json_cells)[:3]} "
        f"only_json={sorted(json_cells - csv_cells)[:3]}"
    )


def test_every_winner_is_a_known_policy(payload: dict) -> None:
    unknown = {c["winner"] for c in payload["cells"]} - KNOWN_POLICIES
    assert not unknown, f"unknown winner labels: {sorted(unknown)}"


def test_every_miss_rate_is_in_unit_interval(csv_rows: list[dict]) -> None:
    bad = [
        (r["graph"], r["app"], r["policy_label"], r["l3_miss_rate"])
        for r in csv_rows
        if not (0.0 <= float(r["l3_miss_rate"]) <= 1.0)
    ]
    assert not bad, f"miss-rate out of [0,1]: {bad[:3]}"


def test_lru_wins_at_least_one_thrash_cell(payload: dict) -> None:
    """Headline paper claim: at tiny L3, pinning strategies thrash and
    classic LRU wins outright on at least one cell where GRASP and POPT
    both regress >= 5 pp.
    """
    matches: list[str] = []
    for s in payload["showdown"]:
        gd = s.get("lru_minus_grasp_pp")
        pd = s.get("lru_minus_popt_pp")
        if gd is None or pd is None:
            continue
        if gd >= 5.0 and pd >= 5.0:
            matches.append(f"{s['graph']}/{s['app']}@{s['l3_size']}")
    assert matches, (
        "No cell shows the paper's 'GRASP+POPT both regress vs LRU "
        "by >= 5 pp' tiny-L3 thrash signature. The small-L3 thrash "
        "story has collapsed — verify the sweep actually used a 4 kB "
        "L3 with tiny L1/L2."
    )


def test_popt_charged_never_wins(payload: dict) -> None:
    """POPT_CHARGED carries POPT overhead bytes; in tiny-L3 regime it
    is expected to be uniformly the *worst* policy (>= all uncharged).
    A win would suggest the overhead accounting silently regressed.
    """
    wins = [c for c in payload["cells"] if c["winner"] == "POPT_CHARGED"]
    assert not wins, (
        f"POPT_CHARGED unexpectedly won {len(wins)} cell(s); the "
        f"overhead-charging variant should never beat its uncharged "
        f"baseline at 4 kB L3."
    )


def test_all_ecg_variants_present(payload: dict) -> None:
    seen = set(payload["summary"]["policy_stats"].keys())
    missing = REQUIRED_ECG_LABELS - seen
    assert not missing, (
        f"ECG variants missing from small_l3_thrash report: {sorted(missing)}. "
        f"Re-run the final_cache_sim sweep with all four ECG modes."
    )


def test_summary_counts_sum_to_total(payload: dict) -> None:
    total = payload["summary"]["n_cells"]
    win_sum = sum(payload["summary"]["win_counts"].values())
    assert win_sum == total, (
        f"sum(win_counts)={win_sum} but n_cells={total}; "
        f"every cell should have exactly one winner."
    )
