"""Test the gem5 literature-anchor invariants.

The gem5 anchor is the cycle-accurate corroboration of the cache_sim
lit-faith sweep on a small graph. Its JSON snapshot lives at
``wiki/data/gem5_anchor.json`` and is regenerated by
``make gem5-anchor`` (or as part of ``make confidence``).

This gate enforces:

1. The on-disk snapshot exists and is well-formed.
2. Every recorded invariant is in ``ok`` state (no ``disagree``).
3. The headline GRASP-vs-LRU result holds for both PR and BC at the
   256 kB L3 (the GRASP-paper headline regime).
4. The asymptote invariant (policies converge at 2 MB) holds for
   both PR and BC.
5. The summary script behaves correctly on synthetic inputs:
   - reports `disagree` when an invariant is violated.
   - reports `missing` when a required cell is absent.
   - reports `disagree` for ``no_error_rows`` when the sweep contains
     error rows for the scoped graph.
"""

from __future__ import annotations

import csv
import importlib.util
import json
import sys
import textwrap
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
SUMMARY_PATH = REPO_ROOT / "scripts/experiments/ecg/gem5_anchor_summary.py"
ANCHOR_JSON = REPO_ROOT / "wiki/data/gem5_anchor.json"


def _load_summary_module():
    spec = importlib.util.spec_from_file_location(
        "gem5_anchor_summary_test_mod", SUMMARY_PATH
    )
    mod = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = mod
    spec.loader.exec_module(mod)  # type: ignore[union-attr]
    return mod


def _write_synthetic_sweep(
    root: Path,
    graph: str,
    app: str,
    rows: list[dict],
    subdir: str = "DBG",
) -> Path:
    """Write a minimal roi_matrix.csv at root/<graph>-<app>/<subdir>/roi_matrix.csv."""
    dest_dir = root / f"{graph}-{app}" / subdir
    dest_dir.mkdir(parents=True, exist_ok=True)
    csv_path = dest_dir / "roi_matrix.csv"
    fieldnames = ["benchmark", "policy", "l3_size", "l3_miss_rate", "section", "status"]
    with csv_path.open("w") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames)
        w.writeheader()
        for r in rows:
            base = {"benchmark": app, "section": "1", "status": "ok"}
            base.update(r)
            w.writerow(base)
    return csv_path


@pytest.fixture(scope="module")
def anchor_snapshot() -> dict:
    if not ANCHOR_JSON.exists():
        pytest.fail(
            f"gem5 anchor snapshot missing: {ANCHOR_JSON}. "
            "Regenerate with `make gem5-anchor`."
        )
    return json.loads(ANCHOR_JSON.read_text())


def test_snapshot_has_invariants(anchor_snapshot: dict) -> None:
    assert "invariants" in anchor_snapshot
    assert len(anchor_snapshot["invariants"]) >= 5, (
        "expected ≥5 invariants (2 headline + 2 asymptote + no_error_rows)"
    )


def test_no_invariant_disagrees(anchor_snapshot: dict) -> None:
    disagreements = [i for i in anchor_snapshot["invariants"] if i["status"] == "disagree"]
    assert not disagreements, (
        "gem5 anchor invariants in disagree state: "
        + ", ".join(f"{d['name']} ({d['detail']})" for d in disagreements)
    )


def test_no_invariant_missing(anchor_snapshot: dict) -> None:
    missing = [i for i in anchor_snapshot["invariants"] if i["status"] == "missing"]
    assert not missing, (
        "gem5 anchor invariants missing data: "
        + ", ".join(f"{m['name']} ({m['detail']})" for m in missing)
    )


@pytest.mark.parametrize("app", ["pr", "bc"])
def test_headline_grasp_le_lru_present(anchor_snapshot: dict, app: str) -> None:
    name = f"GRASP_LE_LRU_headline:{app}@256kB"
    matches = [i for i in anchor_snapshot["invariants"] if i["name"] == name]
    assert matches, f"expected invariant {name}"
    assert matches[0]["status"] == "ok", matches[0]


@pytest.mark.parametrize("app", ["pr", "bc"])
def test_asymptote_present(anchor_snapshot: dict, app: str) -> None:
    name_prefix = f"asymptote_within_"
    matches = [
        i for i in anchor_snapshot["invariants"]
        if i["name"].startswith(name_prefix) and i["name"].endswith(f":{app}@2MB")
    ]
    assert matches, f"expected asymptote invariant for {app}@2MB"
    assert matches[0]["status"] == "ok", matches[0]


# --- behavioural tests against synthetic sweep dirs ---------------------------

def _good_email_eu_core_rows() -> dict[tuple[str, str], list[dict]]:
    """A minimal but invariant-satisfying email-Eu-core sweep."""
    return {
        ("pr", "256kB"): [
            {"policy": "LRU", "l3_size": "256kB", "l3_miss_rate": "0.1320"},
            {"policy": "GRASP", "l3_size": "256kB", "l3_miss_rate": "0.1100"},
            {"policy": "SRRIP", "l3_size": "256kB", "l3_miss_rate": "0.0940"},
        ],
        ("bc", "256kB"): [
            {"policy": "LRU", "l3_size": "256kB", "l3_miss_rate": "0.0286"},
            {"policy": "GRASP", "l3_size": "256kB", "l3_miss_rate": "0.0253"},
            {"policy": "SRRIP", "l3_size": "256kB", "l3_miss_rate": "0.0244"},
        ],
        ("pr", "2MB"): [
            {"policy": "LRU", "l3_size": "2MB", "l3_miss_rate": "0.0050"},
            {"policy": "GRASP", "l3_size": "2MB", "l3_miss_rate": "0.0053"},
            {"policy": "SRRIP", "l3_size": "2MB", "l3_miss_rate": "0.0054"},
        ],
        ("bc", "2MB"): [
            {"policy": "LRU", "l3_size": "2MB", "l3_miss_rate": "0.0019"},
            {"policy": "GRASP", "l3_size": "2MB", "l3_miss_rate": "0.0018"},
            {"policy": "SRRIP", "l3_size": "2MB", "l3_miss_rate": "0.0021"},
        ],
    }


def _materialise_synthetic_sweep(root: Path, per_app_rows: dict[tuple[str, str], list[dict]]) -> None:
    by_app: dict[str, list[dict]] = {}
    for (app, _l3), rows in per_app_rows.items():
        by_app.setdefault(app, []).extend(rows)
    for app, rows in by_app.items():
        _write_synthetic_sweep(root, "email-Eu-core", app, rows)


def test_synthetic_good_sweep_passes(tmp_path: Path) -> None:
    mod = _load_summary_module()
    _materialise_synthetic_sweep(tmp_path, _good_email_eu_core_rows())
    cells = mod.load_cells(tmp_path, "DBG", graphs={"email-Eu-core"})
    invariants = mod.evaluate_invariants(cells)
    statuses = {i.name: i.status for i in invariants}
    assert all(s == "ok" for s in statuses.values()), statuses


def test_synthetic_headline_violation_disagrees(tmp_path: Path) -> None:
    mod = _load_summary_module()
    rows = _good_email_eu_core_rows()
    # Force GRASP to be >> LRU at 256kB for BC — violation
    rows[("bc", "256kB")] = [
        {"policy": "LRU", "l3_size": "256kB", "l3_miss_rate": "0.0100"},
        {"policy": "GRASP", "l3_size": "256kB", "l3_miss_rate": "0.0500"},
        {"policy": "SRRIP", "l3_size": "256kB", "l3_miss_rate": "0.0090"},
    ]
    _materialise_synthetic_sweep(tmp_path, rows)
    cells = mod.load_cells(tmp_path, "DBG", graphs={"email-Eu-core"})
    invariants = mod.evaluate_invariants(cells)
    by_name = {i.name: i for i in invariants}
    assert by_name["GRASP_LE_LRU_headline:bc@256kB"].status == "disagree"


def test_synthetic_missing_asymptote_cell_reports_missing(tmp_path: Path) -> None:
    mod = _load_summary_module()
    rows = _good_email_eu_core_rows()
    # Drop the 2MB cell for PR entirely
    del rows[("pr", "2MB")]
    _materialise_synthetic_sweep(tmp_path, rows)
    cells = mod.load_cells(tmp_path, "DBG", graphs={"email-Eu-core"})
    invariants = mod.evaluate_invariants(cells)
    by_name = {i.name: i for i in invariants}
    assert by_name["asymptote_within_1.0pp:pr@2MB"].status == "missing"


def test_synthetic_error_row_disagrees_on_no_error_rows(tmp_path: Path) -> None:
    mod = _load_summary_module()
    rows = _good_email_eu_core_rows()
    _materialise_synthetic_sweep(tmp_path, rows)
    # Append an extra error row to the bc 256kB CSV manually
    csv_path = tmp_path / "email-Eu-core-bc" / "DBG" / "roi_matrix.csv"
    with csv_path.open("a") as f:
        f.write("bc,POPT,256kB,,1,error\n")
    cells = mod.load_cells(tmp_path, "DBG", graphs={"email-Eu-core"})
    invariants = mod.evaluate_invariants(cells)
    by_name = {i.name: i for i in invariants}
    assert by_name["no_error_rows"].status == "disagree"


def test_graph_filter_excludes_unlisted_graphs(tmp_path: Path) -> None:
    mod = _load_summary_module()
    _materialise_synthetic_sweep(tmp_path, _good_email_eu_core_rows())
    # Also stamp a cit-Patents sweep with an error row that would otherwise fail
    _write_synthetic_sweep(
        tmp_path, "cit-Patents", "bc",
        [{"policy": "LRU", "l3_size": "256kB", "l3_miss_rate": "", "status": "error"}],
    )
    # Without filtering: error row would surface
    cells_all = mod.load_cells(tmp_path, "DBG", graphs=None)
    assert any(c.graph == "cit-Patents" for c in cells_all)
    # With filtering: only email-Eu-core appears
    cells_filtered = mod.load_cells(tmp_path, "DBG", graphs={"email-Eu-core"})
    assert all(c.graph == "email-Eu-core" for c in cells_filtered)
    invariants = mod.evaluate_invariants(cells_filtered)
    assert all(i.status == "ok" for i in invariants)
