"""Derivation-parity gate for wiki/data/corpus_diversity.json (CDV-Der).

The corpus-diversity report is the paper's *did-you-cover-diverse-
topologies?* exhibit: GAPBS's `=== Graph Topology Features ===`
block is scraped from one representative cache_sim log per graph
(PR / LRU / L3=1MB preferred), parsed, and emitted as a structured
JSON list. The paper text quotes specific values from this file
(hub concentration spans, avg degree spans, working set ratios).

Generated by :func:`scripts.experiments.ecg.corpus_diversity.main`
with ``asdict(profile)`` for each :class:`GraphProfile`. The list
order is GRAPH_ORDER (web/citation/social/road/mesh families).

The gate (28 tests, 5 groups) locks every load-bearing rule so
any drift in feature ordering, value coercion, log-preference
order, or JSON write rule fails CI before the artifact ships:

* group 1 (5 tests) — top-level type (list), GRAPH_ORDER tuple,
  FIELDS tuple-of-triples, JSON byte parity (indent=2, NO
  sort_keys, NO trailing newline), GRAPH_LINE regex.
* group 2 (5 tests) — each entry shape (6 dataclass fields:
  graph, log_path, nodes, edges, edges_directed, features),
  features is a dict, features keys ⊆ FIELDS keys, all numeric
  fields are numeric, graphs match GRAPH_ORDER.
* group 3 (5 tests) — _coerce rules (int via int(float(raw));
  float for other kinds; empty/whitespace → None; ValueError
  → None; scientific notation passes).
* group 4 (6 tests) — find_log preference order on a synthetic
  layout (PR/LRU/1MB beats PR/SRRIP/1MB beats any cache_sim_pr_*
  beats fallback to any cache_sim_*).
* group 5 (7 tests) — parse_log on a synthetic log (extracts
  graph card, picks up features, skips missing fields silently,
  honours GRAPH_LINE; collect() honours GRAPH_ORDER iteration
  and explicit-name fallback).
"""

from __future__ import annotations

import json
import sys
from dataclasses import asdict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT))

import pytest  # noqa: E402

from scripts.experiments.ecg import corpus_diversity as cdv  # noqa: E402


DATA = REPO_ROOT / "wiki" / "data"
ARTIFACT = DATA / "corpus_diversity.json"


@pytest.fixture(scope="module")
def artifact() -> list:
    return json.loads(ARTIFACT.read_text())


# ---------------------------------------------------------------------------
# Group 1 — top-level type, GRAPH_ORDER, FIELDS, JSON byte parity (5 tests)
# ---------------------------------------------------------------------------


def test_top_level_is_list(artifact):
    """The JSON is a top-level list, NOT a dict. The paper-claims
    registry already special-cases `isinstance(corpus, list)` — if
    this shape ever flips to dict, the corpus.graph_count claim
    silently breaks."""
    assert isinstance(artifact, list)


def test_graph_order_pinned():
    """GRAPH_ORDER is the 8-tuple of corpus graphs in the canonical
    paper presentation order (small → large by family). The order is
    load-bearing for the per-row markdown layout AND for the JSON
    iteration order — changing it would silently churn the artifact
    on every regen."""
    assert cdv.GRAPH_ORDER == [
        "email-Eu-core",
        "web-Google",
        "cit-Patents",
        "soc-pokec",
        "com-orkut",
        "soc-LiveJournal1",
        "roadNet-CA",
        "delaunay_n19",
    ]


def test_fields_pinned():
    """FIELDS is a 14-tuple of (human_label, key, kind) triples. The
    human_label is the literal GAPBS prefix; the key is the dict-key
    in features; the kind drives _coerce + _fmt branches."""
    assert len(cdv.FIELDS) == 14
    # Spot-check load-bearing entries (the GRASP narrative leans on
    # hub_concentration and working_set_ratio).
    keys = [k for _, k, _ in cdv.FIELDS]
    assert "hub_concentration" in keys
    assert "working_set_ratio" in keys
    assert "clustering_coeff" in keys
    assert "avg_degree" in keys
    # Every triple has exactly three elements (label, key, kind).
    for triple in cdv.FIELDS:
        assert len(triple) == 3
        label, key, kind = triple
        assert isinstance(label, str)
        assert isinstance(key, str)
        assert kind in {"int", "float"}


def test_json_byte_parity_indent2_no_sort_keys_no_trailing_newline(artifact):
    """JSON write rule is fixed: indent=2, NO sort_keys (insertion
    order is load-bearing for diff-friendliness — the dataclass
    field order is the JSON key order), NO trailing newline."""
    raw = ARTIFACT.read_text()
    expected = json.dumps(artifact, indent=2)
    assert raw == expected


def test_graph_line_regex_pattern():
    """GRAPH_LINE regex captures (nodes, edges, dir) from the GAPBS
    `Graph has N nodes and M undirected edges` line. Any change to
    this regex breaks every existing log scrape."""
    m = cdv.GRAPH_LINE.search(
        "Graph has 4847571 nodes and 42851237 undirected edges total"
    )
    assert m is not None
    assert m.group("nodes") == "4847571"
    assert m.group("edges") == "42851237"
    assert m.group("dir") == "undirected"
    # also matches "directed"
    m2 = cdv.GRAPH_LINE.search(
        "Graph has 100 nodes and 50 directed edges"
    )
    assert m2.group("dir") == "directed"


# ---------------------------------------------------------------------------
# Group 2 — entry shape and field-type invariants (5 tests)
# ---------------------------------------------------------------------------


def test_each_entry_has_six_dataclass_fields(artifact):
    """Each entry has exactly the 6 GraphProfile dataclass fields:
    graph, log_path, nodes, edges, edges_directed, features. asdict()
    expands the dataclass in declaration order — adding a field
    without bumping the test would silently churn the artifact."""
    required = {"graph", "log_path", "nodes", "edges", "edges_directed", "features"}
    for p in artifact:
        missing = required - set(p.keys())
        assert not missing, f"{p.get('graph','?')} missing: {missing}"


def test_features_is_dict(artifact):
    """features is always a dict (default_factory=dict)."""
    for p in artifact:
        assert isinstance(p["features"], dict)


def test_features_keys_are_subset_of_fields_keys(artifact):
    """No surprise feature keys: every key in features must be one
    of the 14 FIELDS keys. A typo in parse_log would slip through
    here."""
    allowed = {k for _, k, _ in cdv.FIELDS}
    for p in artifact:
        extra = set(p["features"].keys()) - allowed
        assert not extra, f"{p['graph']} has unknown feature keys: {extra}"


def test_nodes_edges_are_ints_and_nonnegative(artifact):
    """nodes and edges are non-negative ints. edges_directed is a
    bool (asdict preserves bool). A failed GRAPH_LINE match leaves
    the dataclass defaults (0, 0, False)."""
    for p in artifact:
        assert isinstance(p["nodes"], int) and p["nodes"] >= 0
        assert isinstance(p["edges"], int) and p["edges"] >= 0
        assert isinstance(p["edges_directed"], bool)


def test_entries_in_graph_order_subset(artifact):
    """Entries appear in GRAPH_ORDER order (collect() iterates the
    `graphs` arg directly). The artifact may be a SUBSET of
    GRAPH_ORDER (find_log can return None and the graph is skipped)
    but the surviving subset must preserve the original order.
    """
    seen = [p["graph"] for p in artifact]
    indices = [
        cdv.GRAPH_ORDER.index(g) for g in seen if g in cdv.GRAPH_ORDER
    ]
    assert indices == sorted(indices), (
        f"entries out of GRAPH_ORDER: {seen}"
    )


# ---------------------------------------------------------------------------
# Group 3 — _coerce numeric coercion rules (5 tests)
# ---------------------------------------------------------------------------


def test_coerce_int_via_int_of_float():
    """kind='int' returns int(float(raw)) — handles '1.0' and '1e3'
    and negative ints. This is what makes Community Count Estimate
    deserialise correctly when GAPBS prints it as '12.0' instead of
    '12'."""
    assert cdv._coerce("12", "int") == 12
    assert cdv._coerce("12.0", "int") == 12
    assert cdv._coerce("1e3", "int") == 1000
    assert cdv._coerce("-5", "int") == -5


def test_coerce_float_for_non_int_kinds():
    """Any kind other than 'int' returns float(raw). Negative + sci
    notation work; scientific 'e' / 'E' both accepted."""
    assert cdv._coerce("1.5", "float") == 1.5
    assert cdv._coerce("-3.14", "float") == -3.14
    assert cdv._coerce("1.5e-4", "float") == pytest.approx(1.5e-4)
    assert cdv._coerce("0", "float") == 0.0


def test_coerce_empty_or_whitespace_returns_none():
    """An empty or whitespace-only string returns None. parse_log
    treats None as 'feature missing' (the `if value is not None`
    guard at line 108 prevents inserting None into features)."""
    assert cdv._coerce("", "float") is None
    assert cdv._coerce("   ", "int") is None
    assert cdv._coerce("\t\n", "float") is None


def test_coerce_unparseable_returns_none():
    """A non-numeric string returns None, NOT raises ValueError.
    Defensive: a GAPBS log with a corrupt feature value won't crash
    the scraper."""
    assert cdv._coerce("not_a_number", "float") is None
    assert cdv._coerce("12abc", "int") is None
    assert cdv._coerce("--", "float") is None


def test_coerce_strips_whitespace_around_value():
    """_coerce strips whitespace around the raw string before
    parsing. GAPBS prints features as 'Hub Concentration: 0.62 '
    sometimes with trailing whitespace, and the regex group capture
    can include it."""
    assert cdv._coerce("  0.62  ", "float") == 0.62
    assert cdv._coerce("\t12\n", "int") == 12


# ---------------------------------------------------------------------------
# Group 4 — find_log preference order on synthetic layout (6 tests)
# ---------------------------------------------------------------------------


def _make_layout(root: Path, graph: str, subdir: str, log_names: list[str]) -> None:
    """Create the GAPBS-style layout: root/<graph>-pr/<subdir>/logs/*.log"""
    log_dir = root / f"{graph}-pr" / subdir / "logs"
    log_dir.mkdir(parents=True, exist_ok=True)
    for name in log_names:
        (log_dir / name).write_text("placeholder")


def test_find_log_prefers_pr_lru_1mb(tmp_path):
    """Preference 1: PR / LRU / 1MB wins over everything else."""
    _make_layout(
        tmp_path, "web-Google", "lit",
        [
            "cache_sim_pr_LRU_L31MB.log",
            "cache_sim_pr_SRRIP_L31MB.log",
            "cache_sim_pr_GRASP_L34MB.log",
        ],
    )
    found = cdv.find_log(tmp_path, "lit", "web-Google")
    assert found is not None
    assert found.name == "cache_sim_pr_LRU_L31MB.log"


def test_find_log_falls_back_to_srrip_when_lru_missing(tmp_path):
    """Preference 2: PR / SRRIP / 1MB when LRU missing."""
    _make_layout(
        tmp_path, "web-Google", "lit",
        [
            "cache_sim_pr_SRRIP_L31MB.log",
            "cache_sim_pr_GRASP_L34MB.log",
        ],
    )
    found = cdv.find_log(tmp_path, "lit", "web-Google")
    assert found.name == "cache_sim_pr_SRRIP_L31MB.log"


def test_find_log_falls_back_to_any_pr_log(tmp_path):
    """Preference 3: any cache_sim_pr_*.log (sorted) when the
    primary two are missing."""
    _make_layout(
        tmp_path, "web-Google", "lit",
        [
            "cache_sim_pr_GRASP_L34MB.log",
            "cache_sim_pr_POPT_L34MB.log",
        ],
    )
    found = cdv.find_log(tmp_path, "lit", "web-Google")
    assert found is not None
    # sorted order → cache_sim_pr_GRASP_L34MB.log comes first
    assert found.name == "cache_sim_pr_GRASP_L34MB.log"


def test_find_log_falls_back_to_other_app_dir(tmp_path):
    """Last resort: search any <graph>-* app dir for a cache_sim
    log. Required when the PR sweep didn't run for that graph."""
    # No "web-Google-pr" directory — only "web-Google-bfs"
    log_dir = tmp_path / "web-Google-bfs" / "lit" / "logs"
    log_dir.mkdir(parents=True)
    (log_dir / "cache_sim_bfs_LRU_L31MB.log").write_text("x")
    found = cdv.find_log(tmp_path, "lit", "web-Google")
    assert found is not None
    assert found.name == "cache_sim_bfs_LRU_L31MB.log"


def test_find_log_returns_none_when_no_logs(tmp_path):
    """No logs anywhere → return None (collect() then warns + skips
    the graph; the artifact will be a subset of GRAPH_ORDER)."""
    found = cdv.find_log(tmp_path, "lit", "web-Google")
    assert found is None


def test_find_log_uses_sweep_subdir(tmp_path):
    """find_log restricts to the configured sweep_subdir (e.g. 'lit'
    vs 'roi'). A different subdir's logs are NOT returned."""
    # Make a log only in 'roi' subdir
    log_dir = tmp_path / "web-Google-pr" / "roi" / "logs"
    log_dir.mkdir(parents=True)
    (log_dir / "cache_sim_pr_LRU_L31MB.log").write_text("x")
    # Asking for 'lit' subdir returns None
    assert cdv.find_log(tmp_path, "lit", "web-Google") is None
    # Asking for 'roi' subdir finds it
    assert cdv.find_log(tmp_path, "roi", "web-Google") is not None


# ---------------------------------------------------------------------------
# Group 5 — parse_log + collect end-to-end on synthetic data (7 tests)
# ---------------------------------------------------------------------------


SYNTHETIC_LOG = """\
GAPBS preamble blah
Graph has 4847571 nodes and 42851237 undirected edges (some extra stuff)

=== Graph Topology Features ===
Clustering Coefficient: 0.123
Avg Path Length: 5.6
Diameter Estimate: 10.0
Community Count Estimate: 42.0
Degree Variance: 1234.5
Hub Concentration: 0.62
Avg Degree: 17.7
Graph Density: 0.0001
Modularity: 0.45
Forward Edge Fraction: 0.5
Working Set Ratio: 29.4
Vertex Significance Skewness: 1.2
Window Neighbor Overlap: 0.33
Sampled Locality Score: 0.10
"""


def test_parse_log_extracts_graph_card(tmp_path):
    """parse_log pulls nodes/edges/edges_directed from the GAPBS
    graph card line."""
    log = tmp_path / "soc-LiveJournal1-pr" / "lit" / "logs" / "cache_sim_pr_LRU_L31MB.log"
    log.parent.mkdir(parents=True)
    log.write_text(SYNTHETIC_LOG)
    p = cdv.parse_log(log)
    assert p.nodes == 4847571
    assert p.edges == 42851237
    assert p.edges_directed is False


def test_parse_log_extracts_all_features(tmp_path):
    """parse_log populates features dict with every present field."""
    log = tmp_path / "soc-LiveJournal1-pr" / "lit" / "logs" / "cache_sim_pr_LRU_L31MB.log"
    log.parent.mkdir(parents=True)
    log.write_text(SYNTHETIC_LOG)
    p = cdv.parse_log(log)
    assert p.features["clustering_coeff"] == pytest.approx(0.123)
    assert p.features["hub_concentration"] == pytest.approx(0.62)
    assert p.features["community_count"] == 42  # int kind
    assert isinstance(p.features["community_count"], int)
    assert p.features["working_set_ratio"] == pytest.approx(29.4)


def test_parse_log_silently_drops_missing_features(tmp_path):
    """parse_log emits ONLY features actually present in the log.
    A truncated log without `Modularity: ...` leaves that key out
    of features (not present-as-None). This is the
    `if value is not None: features[key] = value` guard at line 108."""
    truncated = "\n".join(
        [l for l in SYNTHETIC_LOG.splitlines()
         if not l.startswith("Modularity")]
    )
    log = tmp_path / "x-pr" / "lit" / "logs" / "cache_sim_pr_LRU_L31MB.log"
    log.parent.mkdir(parents=True)
    log.write_text(truncated)
    p = cdv.parse_log(log)
    assert "modularity" not in p.features
    # other features still present
    assert "hub_concentration" in p.features


def test_parse_log_handles_missing_graph_card(tmp_path):
    """If the GAPBS graph card line is missing, nodes/edges stay at
    dataclass defaults (0, 0, False). The dataclass survives."""
    log_text = "=== Graph Topology Features ===\nHub Concentration: 0.5\n"
    log = tmp_path / "x-pr" / "lit" / "logs" / "cache_sim_pr_LRU_L31MB.log"
    log.parent.mkdir(parents=True)
    log.write_text(log_text)
    p = cdv.parse_log(log)
    assert p.nodes == 0
    assert p.edges == 0
    assert p.edges_directed is False
    assert p.features.get("hub_concentration") == 0.5


def test_parse_log_directed_edges(tmp_path):
    """parse_log distinguishes 'directed' vs 'undirected'."""
    log_text = "Graph has 100 nodes and 50 directed edges\n"
    log = tmp_path / "x-pr" / "lit" / "logs" / "cache_sim_pr_LRU_L31MB.log"
    log.parent.mkdir(parents=True)
    log.write_text(log_text)
    p = cdv.parse_log(log)
    assert p.edges_directed is True


def test_collect_iterates_graphs_in_order(tmp_path):
    """collect() iterates the `graphs` argument in order; the result
    list preserves that order. Skipped graphs (no log) drop out
    silently with a stderr warning."""
    # Create logs for graphs in NON-canonical order to prove that
    # the result order follows the input arg, not filesystem order.
    for g in ["cit-Patents", "email-Eu-core", "web-Google"]:
        _make_layout(tmp_path, g, "lit", ["cache_sim_pr_LRU_L31MB.log"])
        (tmp_path / f"{g}-pr" / "lit" / "logs"
         / "cache_sim_pr_LRU_L31MB.log").write_text(SYNTHETIC_LOG)
    profiles = cdv.collect(
        tmp_path, "lit", ["email-Eu-core", "web-Google", "cit-Patents"]
    )
    assert [p.graph for p in profiles] == [
        "email-Eu-core", "web-Google", "cit-Patents"
    ]


def test_collect_uses_explicit_graph_name_over_parse_guess(tmp_path):
    """collect() overrides parse_log's directory-derived graph name
    with the explicit arg name (line 165). This is what allows
    graphs like 'soc-LiveJournal1' to round-trip through the
    '<graph>-<app>' directory split correctly even though the
    rsplit on '-' would otherwise truncate the name."""
    # Set up the layout but with the directory layout that parse_log
    # would mis-guess (soc-LiveJournal1 splits to soc-LiveJournal1).
    g = "soc-LiveJournal1"
    _make_layout(tmp_path, g, "lit", ["cache_sim_pr_LRU_L31MB.log"])
    (tmp_path / f"{g}-pr" / "lit" / "logs"
     / "cache_sim_pr_LRU_L31MB.log").write_text(SYNTHETIC_LOG)
    profiles = cdv.collect(tmp_path, "lit", [g])
    assert len(profiles) == 1
    # The explicit name in `graphs` overrides parse_log's guess
    assert profiles[0].graph == g
    # asdict() round-trips cleanly to the JSON shape
    out = asdict(profiles[0])
    assert set(out.keys()) == {
        "graph", "log_path", "nodes", "edges", "edges_directed", "features",
    }
