"""Gate 87 — artifact-catalog completeness.

Cross-artifact integrity gate: every machine-readable JSON artifact under
``wiki/data/`` must be registered in ``wiki/data/artifact_catalog.json``
(via the ``CATALOG`` list in ``scripts/experiments/ecg/artifact_catalog.py``)
or explicitly allowlisted in :data:`META_ALLOWLIST` below.

This catches the failure mode where a new generator ships its JSON into
``wiki/data/`` but the catalog (and therefore the paper appendix, the
HANDOFF and the reader) silently never learns about it. We hit that
failure mode for ``paper_baseline_table.json`` once already; this gate
makes a recurrence impossible.

Allowlist policy:
  * ``artifact_catalog.json`` itself is self-referential (it is the
    catalog) and is not required to register itself.
  * Hand-curated INPUTS under ``wiki/data/`` (e.g. ``*_postfix.json``
    snapshots that a generator consumes but does not regenerate) are
    allowlisted with a documented reason. They are not paper artifacts
    in their own right — they are pinned fixtures.

The gate also asserts the inverse: every registered artifact path under
``wiki/data/`` actually exists on disk and points at a real file.
"""

from __future__ import annotations

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
CATALOG_JSON = REPO_ROOT / "wiki" / "data" / "artifact_catalog.json"
WIKI_DATA = REPO_ROOT / "wiki" / "data"

# Self-referential / meta artifacts + hand-curated inputs that the
# catalog is not required to register. Keep this list small; every
# addition is a load-bearing decision about what counts as a paper
# artifact vs a pinned input fixture.
META_ALLOWLIST: set[str] = {
    "wiki/data/artifact_catalog.json",
    # Gate 238 ECG-Parity curated input: 54-obs snapshot from
    # email-Eu-core proof_matrix.csv. Not regenerated by any in-repo
    # generator (it is the INPUT to lit_faith_ecg_parity.py), so it has
    # no generator/gate of its own and is exempt from catalog
    # registration. Its hash is locked indirectly via the gate-238
    # pytest, which asserts the file's schema + per-row invariants.
    "wiki/data/ecg_substrate_parity_postfix.json",
    # Gate 239 ECG-Gem5-Parity curated input: 12-obs snapshot from the
    # email-Eu-core PR gem5 bracket sweep (roi_matrix.csv). Same pattern
    # as gate 238: hand-curated INPUT to lit_faith_ecg_gem5_parity.py,
    # locked via the gate-239 pytest schema/per-row invariants.
    "wiki/data/ecg_gem5_parity_postfix.json",
}


def _entries() -> list[dict]:
    return json.loads(CATALOG_JSON.read_text())["entries"]


def _registered_json_artifacts() -> set[str]:
    out: set[str] = set()
    for e in _entries():
        a = e.get("artifact")
        if a and a.endswith(".json") and a.startswith("wiki/data/"):
            out.add(a)
    return out


def _on_disk_json_artifacts() -> list[str]:
    return sorted(
        str(p.relative_to(REPO_ROOT))
        for p in WIKI_DATA.glob("*.json")
    )


# ---------------------------------------------------------------------------
# Completeness invariants
# ---------------------------------------------------------------------------

def test_catalog_json_loads_and_has_entries():
    data = json.loads(CATALOG_JSON.read_text())
    assert "entries" in data, "catalog missing 'entries' key"
    assert "summary" in data, "catalog missing 'summary' key"
    assert isinstance(data["entries"], list)
    assert len(data["entries"]) >= 71, "catalog entry count regressed below floor"


def test_every_wiki_json_is_registered_or_allowlisted():
    on_disk = set(_on_disk_json_artifacts())
    registered = _registered_json_artifacts()
    missing = sorted(on_disk - registered - META_ALLOWLIST)
    assert not missing, (
        "wiki/data JSON artifacts missing from artifact_catalog.json: "
        f"{missing} — register them in scripts/experiments/ecg/"
        "artifact_catalog.py CATALOG (or add to META_ALLOWLIST if "
        "they are genuinely self-referential)."
    )


def test_meta_allowlist_files_actually_exist():
    """The allowlist is not a dumping ground — every entry on it must
    still exist on disk, so removed artifacts are caught."""
    for rel in META_ALLOWLIST:
        p = REPO_ROOT / rel
        assert p.is_file(), f"allowlisted meta-artifact missing on disk: {rel}"


def test_meta_allowlist_does_not_hide_a_real_catalog_entry():
    """If an allowlisted artifact ever shows up in the catalog, the
    allowlist exception is no longer needed and should be removed."""
    registered = _registered_json_artifacts()
    overlap = META_ALLOWLIST & registered
    assert not overlap, (
        f"allowlist redundantly hides registered artifacts: {sorted(overlap)} "
        "— remove them from META_ALLOWLIST."
    )


# ---------------------------------------------------------------------------
# Existence + per-entry integrity invariants
# ---------------------------------------------------------------------------

def test_every_registered_artifact_exists_on_disk():
    missing = []
    for e in _entries():
        a = e.get("artifact")
        if not a:
            continue
        p = REPO_ROOT / a
        if not p.is_file():
            missing.append(a)
    assert not missing, f"registered artifacts missing on disk: {missing}"


def test_every_registered_generator_exists_on_disk():
    missing = []
    for e in _entries():
        g = e.get("generator")
        if not g:
            continue
        p = REPO_ROOT / g
        if not p.is_file():
            missing.append((e["id"], g))
    assert not missing, f"registered generators missing on disk: {missing}"


def test_every_registered_gate_exists_on_disk():
    missing = []
    for e in _entries():
        g = e.get("gate")
        if not g:
            continue
        p = REPO_ROOT / g
        if not p.is_file():
            missing.append((e["id"], g))
    assert not missing, f"registered gates missing on disk: {missing}"


def test_every_entry_has_required_keys():
    required = {"id", "label", "generator", "gate", "artifact", "summary"}
    for e in _entries():
        missing = required - set(e.keys())
        assert not missing, f"entry {e.get('id','?')} missing keys: {missing}"


def test_entry_ids_are_unique():
    ids = [e["id"] for e in _entries()]
    dups = {x for x in ids if ids.count(x) > 1}
    assert not dups, f"duplicate catalog entry ids: {sorted(dups)}"


def test_artifact_paths_are_unique():
    paths = [e["artifact"] for e in _entries()]
    dups = {x for x in paths if paths.count(x) > 1}
    assert not dups, f"duplicate catalog artifact paths: {sorted(dups)}"


def test_summary_counts_match_entry_count():
    data = json.loads(CATALOG_JSON.read_text())
    assert data["summary"]["n_entries"] == len(data["entries"])


def test_no_entry_is_missing_artifact_per_summary():
    """The catalog's own per-entry existence flags must all be True."""
    bad = [e["id"] for e in _entries() if not e.get("artifact_exists")]
    assert not bad, f"catalog flags these artifacts as missing on disk: {bad}"
    bad_g = [e["id"] for e in _entries() if not e.get("generator_exists")]
    assert not bad_g, f"catalog flags these generators as missing: {bad_g}"
    bad_t = [e["id"] for e in _entries() if not e.get("gate_exists")]
    assert not bad_t, f"catalog flags these gates as missing: {bad_t}"


def test_paper_baseline_table_is_registered():
    """Regression guard for the original gap that motivated this gate:
    paper_baseline_table.json shipped to wiki/data/ without being
    catalogued. Lock its registration explicitly."""
    ids = {e["id"] for e in _entries()}
    assert "paper_baseline_table" in ids, (
        "paper_baseline_table.json must remain registered in "
        "scripts/experiments/ecg/artifact_catalog.py CATALOG."
    )


def test_catalog_summary_announces_current_gate_count():
    """The dashboard summary string is the catalog's headline number;
    drift between the gate count and this string fails the gate. The
    exact number is not pinned here (every gate addition bumps it), but
    the format is."""
    data = json.loads(CATALOG_JSON.read_text())
    entries = data["entries"]
    dash = next(
        (e for e in entries if e["id"] == "confidence_dashboard"),
        None,
    )
    assert dash is not None, "confidence_dashboard entry missing from catalog"
    summ = dash["summary"]
    assert "gates today" in summ, (
        f"dashboard summary does not announce 'gates today': {summ!r}"
    )
