"""Derivation-parity gate for wiki/data/small_l3_thrash.json (SLT-Der).

The small-L3 thrash report is the paper's *below-the-knee* exhibit:
at a 4 kB L3 the working set overflows even the hot region, and the
naive LRU baseline routinely beats the GRASP/POPT pinning policies.
The report quantifies how often that happens, by how many pp, and
whether the ECG variants recover the loss.

Generated by
:func:`scripts.experiments.ecg.small_l3_thrash_report.main` from
``final_cache_sim/combined_roi_matrix.csv`` files. The JSON payload
carries four user-visible objects (summary.win_counts, summary.
policy_stats, cells (per-cell winners), and showdown (per-cell LRU
vs GRASP/POPT deltas)) plus a fixed schema_version=1 contract.

The gate (24 tests, 5 groups) locks every load-bearing rule so any
drift in policy ordering, tie-break behaviour, aggregation logic,
or JSON write rule fails CI before the artifact ships:

* group 1 (5 tests) — top-level shape, schema_version contract,
  POLICY_LABEL_ORDER tuple, JSON byte parity (sort_keys=True,
  indent=2, trailing newline), sources list shape.
* group 2 (5 tests) — _winner deterministic tie-break (sort by
  miss_rate then POLICY_LABEL_ORDER index; unknown labels go to the
  end via len(POLICY_LABEL_ORDER) sentinel; margin_pp formula).
* group 3 (5 tests) — _aggregate winners construction (one entry
  per (graph,app,l3_size) cell sorted by key; cells == winners;
  win_counts equals Counter over winners).
* group 4 (5 tests) — per-policy aggregates (skip empty labels;
  emitted in POLICY_LABEL_ORDER iteration order; n_cells, mean,
  median, min, max, wins fields all required and consistent with
  raw row distribution).
* group 5 (4 tests) — showdown construction (requires LRU present;
  grasp/popt may be None; lru_minus_X_pp = (X - LRU) × 100 pp;
  Counter sums match summary.n_cells; build self-consistency via
  re-running the generator's aggregator over hashed cells).
"""

from __future__ import annotations

import csv
import json
import statistics
import sys
from collections import Counter
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT))

import pytest  # noqa: E402

from scripts.experiments.ecg import small_l3_thrash_report as slt  # noqa: E402


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

DATA = REPO_ROOT / "wiki" / "data"
ARTIFACT = DATA / "small_l3_thrash.json"
CSV_ARTIFACT = DATA / "small_l3_thrash.csv"


@pytest.fixture(scope="module")
def artifact() -> dict:
    return json.loads(ARTIFACT.read_text())


@pytest.fixture(scope="module")
def csv_rows() -> list[dict]:
    """Load the companion CSV (one row per (graph,app,policy_label) cell).

    The CSV is the materialised raw-rows projection — it's what the
    aggregator builds the JSON summary over.
    """
    if not CSV_ARTIFACT.exists():
        pytest.skip(f"{CSV_ARTIFACT} missing")
    out: list[dict] = []
    with CSV_ARTIFACT.open(newline="") as fh:
        for r in csv.DictReader(fh):
            if r.get("l3_miss_rate") in (None, ""):
                continue
            out.append({
                **r,
                "l3_miss_rate": float(r["l3_miss_rate"]),
            })
    return out


# ---------------------------------------------------------------------------
# Group 1 — top-level shape, constants, JSON byte-parity (5 tests)
# ---------------------------------------------------------------------------


def test_top_level_keys(artifact):
    """The JSON has exactly five top-level keys; no field drifts in."""
    assert set(artifact.keys()) == {
        "schema_version", "sources", "summary", "cells", "showdown",
    }


def test_schema_version_contract(artifact):
    """schema_version is pinned at 1 — bump deliberately on shape change."""
    assert artifact["schema_version"] == 1


def test_policy_label_order_pinned():
    """POLICY_LABEL_ORDER is the 9-tuple that drives tie-break and per-policy
    iteration order. The order is load-bearing — changing it would silently
    change winners on tied cells and the policy_stats table layout.
    """
    assert slt.POLICY_LABEL_ORDER == [
        "LRU",
        "SRRIP",
        "GRASP",
        "POPT",
        "POPT_CHARGED",
        "ECG_DBG_ONLY",
        "ECG_DBG_PRIMARY",
        "ECG_DBG_PRIMARY_CHARGED",
        "ECG_POPT_PRIMARY",
    ]


def test_json_byte_parity_sort_keys_indent2_trailing_newline(artifact):
    """JSON write rule is fixed: sort_keys=True, indent=2, AND a literal
    trailing '\\n' (see _emit_json). The trailing newline is the
    POSIX-style line terminator the writer emits — diff-tools and
    `git diff` both expect it, so removing it would dirty every line
    of the artifact on every commit."""
    raw = ARTIFACT.read_text()
    expected = json.dumps(artifact, indent=2, sort_keys=True) + "\n"
    assert raw == expected


def test_sources_is_sorted_unique_list(artifact):
    """`sources` is sorted-unique by construction (set + sorted). A
    duplicate source would mean the CSV loader processed the same
    sweep twice (double-counted rows)."""
    src = artifact["sources"]
    assert isinstance(src, list)
    assert src == sorted(set(src)), "sources must be sorted-unique"
    for s in src:
        # All sources should be relative paths under results/
        assert isinstance(s, str)
        assert s, "empty source path"


# ---------------------------------------------------------------------------
# Group 2 — _winner deterministic tie-break (5 tests)
# ---------------------------------------------------------------------------


def _row(label: str, miss: float) -> dict:
    return {"policy_label": label, "l3_miss_rate": miss}


def test_winner_picks_lowest_miss_rate():
    """Lowest miss rate wins outright when there's no tie."""
    cell = [_row("LRU", 0.5), _row("GRASP", 0.3), _row("POPT", 0.4)]
    w, _ru, _m = slt._winner(cell)
    assert w["policy_label"] == "GRASP"


def test_winner_tie_break_uses_policy_label_order():
    """On an exact tie, the earlier-in-POLICY_LABEL_ORDER policy wins.
    LRU is index 0 (paper's narrative-critical baseline), so LRU
    breaks ties against GRASP/POPT/SRRIP at the tiny L3 - this is
    intentional because the report leads with LRU dominance."""
    cell = [_row("GRASP", 0.5), _row("LRU", 0.5), _row("POPT", 0.5)]
    w, _ru, _m = slt._winner(cell)
    assert w["policy_label"] == "LRU"


def test_winner_unknown_label_sorts_to_end():
    """An unknown policy_label sorts after all known labels (sentinel
    idx == len(POLICY_LABEL_ORDER)). This prevents a typo in the
    upstream CSV from silently winning a tied cell."""
    cell = [_row("LRU", 0.5), _row("UNKNOWN_TYPO", 0.5)]
    w, _ru, _m = slt._winner(cell)
    assert w["policy_label"] == "LRU"


def test_winner_margin_pp_formula():
    """margin_pp = (runner_up.miss - winner.miss) × 100. Always ≥ 0."""
    cell = [_row("LRU", 0.500), _row("GRASP", 0.300), _row("POPT", 0.450)]
    w, ru, margin = slt._winner(cell)
    assert w["policy_label"] == "GRASP"
    assert ru["policy_label"] == "POPT"  # next lowest miss
    assert margin == pytest.approx((0.450 - 0.300) * 100.0, abs=1e-9)
    assert margin >= 0


def test_winner_single_row_runner_up_is_self():
    """When a cell has a single row, runner_up = winner (no IndexError
    leaks). margin_pp is 0 in that degenerate case."""
    cell = [_row("LRU", 0.5)]
    w, ru, margin = slt._winner(cell)
    assert w is ru
    assert margin == 0.0


# ---------------------------------------------------------------------------
# Group 3 — _aggregate winners + cells parity (5 tests)
# ---------------------------------------------------------------------------


def test_cells_one_entry_per_cell(artifact, csv_rows):
    """`cells` has exactly one entry per (graph, app, l3_size) cell —
    the CSV-side cell count is the source of truth.
    """
    cell_keys = {(r["graph"], r["app"], r["l3_size"]) for r in csv_rows}
    assert len(artifact["cells"]) == len(cell_keys)
    assert artifact["summary"]["n_cells"] == len(cell_keys)


def test_cells_sorted_by_key(artifact):
    """Cells are emitted in sorted (graph, app, l3_size) order. Sort
    stability matters for diff-friendly artifacts."""
    keys = [(c["graph"], c["app"], c["l3_size"]) for c in artifact["cells"]]
    assert keys == sorted(keys)


def test_winners_have_required_fields(artifact):
    """Each winner entry carries graph/app/l3_size and winner +
    runner_up + miss rates + margin_pp."""
    required = {
        "graph", "app", "l3_size",
        "winner", "winner_miss_rate",
        "runner_up", "runner_up_miss_rate",
        "margin_pp",
    }
    for c in artifact["cells"]:
        missing = required - set(c.keys())
        assert not missing, f"{c.get('graph','?')}/{c.get('app','?')} missing: {missing}"


def test_win_counts_matches_counter_over_winners(artifact):
    """summary.win_counts is exactly Counter(winners). A drift here
    would invalidate the headline 'LRU wins 5 / 9 cells at 4 kB' claim."""
    rebuilt = Counter(c["winner"] for c in artifact["cells"])
    assert dict(rebuilt) == artifact["summary"]["win_counts"]


def test_win_counts_total_equals_n_cells(artifact):
    """Sum of win_counts == n_cells (every cell has exactly one winner)."""
    assert sum(artifact["summary"]["win_counts"].values()) == (
        artifact["summary"]["n_cells"]
    )


# ---------------------------------------------------------------------------
# Group 4 — policy_stats consistency with CSV row distribution (5 tests)
# ---------------------------------------------------------------------------


def test_policy_stats_only_labels_with_rows(artifact, csv_rows):
    """policy_stats keys = labels that appear in csv_rows (no empty
    entries, no missing labels). The generator's `if not vals: continue`
    branch is what enforces this."""
    labels_in_csv = {r["policy_label"] for r in csv_rows}
    labels_in_stats = set(artifact["summary"]["policy_stats"].keys())
    assert labels_in_stats == labels_in_csv


def test_policy_stats_required_fields(artifact):
    """Each policy_stats entry carries n_cells, mean, median, min,
    max, wins."""
    required = {
        "n_cells", "mean_miss_rate", "median_miss_rate",
        "min_miss_rate", "max_miss_rate", "wins",
    }
    for label, st in artifact["summary"]["policy_stats"].items():
        missing = required - set(st.keys())
        assert not missing, f"{label} missing: {missing}"


def test_policy_stats_n_cells_matches_csv_row_count(artifact, csv_rows):
    """n_cells == number of CSV rows for that policy label (each label
    contributes one row per (graph,app,l3_size) cell)."""
    by_label: dict[str, list[float]] = {}
    for r in csv_rows:
        by_label.setdefault(r["policy_label"], []).append(r["l3_miss_rate"])
    for label, st in artifact["summary"]["policy_stats"].items():
        assert st["n_cells"] == len(by_label[label])


def test_policy_stats_min_le_median_le_max(artifact):
    """min ≤ median ≤ max for every policy. A violation means the
    statistics computation is broken."""
    for label, st in artifact["summary"]["policy_stats"].items():
        assert st["min_miss_rate"] <= st["median_miss_rate"] <= (
            st["max_miss_rate"] + 1e-12
        ), f"{label} order violated"


def test_policy_stats_mean_median_match_csv_distribution(artifact, csv_rows):
    """mean / median match what statistics.{mean,median} would compute
    over the raw CSV miss-rate distribution for that label."""
    by_label: dict[str, list[float]] = {}
    for r in csv_rows:
        by_label.setdefault(r["policy_label"], []).append(r["l3_miss_rate"])
    for label, st in artifact["summary"]["policy_stats"].items():
        vals = by_label[label]
        assert st["mean_miss_rate"] == pytest.approx(
            statistics.mean(vals), abs=1e-9
        )
        assert st["median_miss_rate"] == pytest.approx(
            statistics.median(vals), abs=1e-9
        )
        assert st["min_miss_rate"] == pytest.approx(min(vals), abs=1e-9)
        assert st["max_miss_rate"] == pytest.approx(max(vals), abs=1e-9)


# ---------------------------------------------------------------------------
# Group 5 — showdown construction + counts integrity (4 tests)
# ---------------------------------------------------------------------------


def test_showdown_one_entry_per_cell_with_lru(artifact, csv_rows):
    """showdown emits one entry per cell that has an LRU row. Cells
    without LRU are silently skipped (`if lru is None: continue`)."""
    by_cell: dict = {}
    for r in csv_rows:
        by_cell.setdefault(
            (r["graph"], r["app"], r["l3_size"]), set()
        ).add(r["policy_label"])
    cells_with_lru = sum(1 for v in by_cell.values() if "LRU" in v)
    assert len(artifact["showdown"]) == cells_with_lru


def test_showdown_lru_minus_grasp_pp_formula(artifact):
    """lru_minus_grasp_pp = (grasp_miss - lru_miss) × 100 (so POSITIVE
    means GRASP is worse than LRU — that's the paper's 'pinning
    thrashes when L3 is tiny' narrative). Same rule for POPT."""
    for s in artifact["showdown"]:
        if s["grasp_miss"] is not None:
            expected = (s["grasp_miss"] - s["lru_miss"]) * 100.0
            assert s["lru_minus_grasp_pp"] == pytest.approx(expected, abs=1e-9)
        else:
            assert s["lru_minus_grasp_pp"] is None
        if s["popt_miss"] is not None:
            expected = (s["popt_miss"] - s["lru_miss"]) * 100.0
            assert s["lru_minus_popt_pp"] == pytest.approx(expected, abs=1e-9)
        else:
            assert s["lru_minus_popt_pp"] is None


def test_showdown_required_fields(artifact):
    """Each showdown entry carries graph/app/l3_size + lru_miss +
    grasp_miss/popt_miss + the two deltas (positionally null when
    grasp/popt absent)."""
    required = {
        "graph", "app", "l3_size",
        "lru_miss", "grasp_miss", "popt_miss",
        "lru_minus_grasp_pp", "lru_minus_popt_pp",
    }
    for s in artifact["showdown"]:
        missing = required - set(s.keys())
        assert not missing, f"showdown missing: {missing}"


def test_aggregate_self_consistency(csv_rows):
    """Re-running _aggregate over the CSV rows reproduces the same
    n_cells, win_counts, policy_stats keys, and showdown length the
    on-disk artifact carries. This is the end-to-end byte-level
    parity check: any drift between the live aggregator and the
    persisted artifact fires here.
    """
    rebuilt = slt._aggregate(csv_rows)
    on_disk = json.loads(ARTIFACT.read_text())
    assert rebuilt["n_cells"] == on_disk["summary"]["n_cells"]
    assert rebuilt["n_rows"] == on_disk["summary"]["n_rows"]
    assert dict(rebuilt["win_counts"]) == on_disk["summary"]["win_counts"]
    assert set(rebuilt["policy_stats"].keys()) == set(
        on_disk["summary"]["policy_stats"].keys()
    )
    assert len(rebuilt["showdown"]) == len(on_disk["showdown"])
